services:
  web_dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - database

  web_prod:
    image: animesh867/news-app-ai:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= {{ POSTGRES_PASSWORD }}
      - POSTGRES_DB=news_app
    volumes:
      - db_data:/var/lib/postgresql/data
    # secrets:
    #   - postgres_password
volumes:
  db_data:

secrets:
  env_file:
    file: .env
#   postgres_password:
#     file: ./secrets/postgres_password.txt
